### ISSUE TITLE
PHPファイルの読み込みでサイドエフェクトが発生しないようにする

### ISSUE THREAD

**Issue by fumikito** [tarosky/Cavalcade-Runner#78]
PHPに限らず、処理と定義をわける→ [Avoid Side effect](https://qiita.com/rana_kualu/items/87ff47935f544441237c#avoid-side-effects)

https://github.com/tarosky/Cavalcade-Runner/blame/677586e48f0ff502328a9fa8bed42c0c3c5d513e/inc/healthcheck-eip.php#L20

値を保持したい場合は、クラスにしてメンバー変数などにするか、関数の場合は [static変数](https://www.php.net/manual/ja/language.variables.scope.php#language.variables.scope.static) を使う

```php
/**
 * トークンを取得する
 * @return string
 * @throw Exception
 */
function get_token() {
    static $token = null;
    static $tried   = 0;
    if ( is_null( $token ) ) {
         // まだ実行されてない？
        if ( ! $tried ) {
            $tried++;
            $token = get_fresh_token();
        } elseif ( $tried < MAX_RETRY ) {
            // まだリトライ可能
            $tried++;
            $token = renew_token( $token ); // renew_token は失敗するとnullを返す
        } else {
             trow new Exception( 'トークンが取れませんでした。' );
        }
    }
    return $token;
}

```

あとは呼び出し側を工夫するか、[ジェネレータ](https://www.php.net/manual/ja/language.generators.syntax.php) を使うかなどとして、トークンを利用する処理が「最大3回までリトライを許容しつつトークン取得を試み続ける」という使い方をすればよいと思います。

**Comment by harai** [comment]
ありがとうございます。PHPでジェネレータが使えるようになっていたのは知りませんでした。例のコードはIPv6対応が終われば不要になるので手は加えませんが、今後PHPのコードを書く際の参考にしたいです。
